title: Your Name
description: A brief description of your portfolio.
baseurl: ""
url: "https://username.github.io" # Replace with your GitHub username
theme: jekyll-theme-minimal # You can change this to any theme you prefer
